language: php
php:
  - '7.3'
  - '7.4'
  - '8.0'

sudo: false

before_install:
  - composer self-update --stable -n

install:
  - composer install --prefer-dist -n -o

script:
  - ./vendor/bin/phpunit --coverage-text=build/cover.txt

after_script:
